Port exploit to Python 3 and new system:

* chall 16
